name: Deploy PHP to IsardVDI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Deploy por SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          REMOTE_PORT: ${{ secrets.PORT }}
          SOURCE: "./"
          TARGET: ${{ secrets.TARGET_DIR }}
          EXCLUDE: "/.git/, /.github/"
